apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kcert.fullname" . }}
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    app: {{ include "kcert.fullname" . }}
    {{- if .Values.forHelm }}
    {{- include "kcert.labels" . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kcert.fullname" . }}
      {{- if .Values.forHelm }}
      {{- include "kcert.selectorLabels" . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "kcert.fullname" . }}
        {{- if .Values.forHelm }}
        {{- include "kcert.selectorLabels" . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "kcert.fullname" . }}
      containers:
      - name: {{ include "kcert.fullname" . }}
        image: {{ required "kcertImage is required" .Values.kcertImage }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        ports:
        - containerPort: 80
          name: http
        - containerPort: 8080
          name: http-admin
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
      env:
      {{- range $key, $value := .Values.env }}
      - name: "{{ $key }}"
        value: "{{ $value }}"
      {{- end }}
      {{- range $secret := .Values.envSecrets }}
      - name: "{{ $secret.name }}"
        valueFrom:
          secretKeyRef:
            name: "{{ $secret.secretName }}"
            key: "{{ $secret.secretKey }}"
      {{- end }}
